#ifndef _____OgreEventArgs_h_
#define _____OgreEventArgs_h_

// Start of Ogre namespace section
namespace Ogre
{
	/*!
	\brief
		Base class used as the argument to all subscribers Event object.

		The base EventArgs class does not contain any useful information, it is intended
		to be specialised for each type of event that can be generated by objects within
		the system.  The use of this base class allows all event subscribers to have the
		same function signature.

		The \a handled field is used to signal whether an event was actually handled or not.  While
		the event system does not look at this value, code at a higher level can use it to determine
		how far to propagate an event.
	*/
	class OgreSystem_Export_API EventArgs
	{
	public:
		/*************************************************************************
			Construction
		*************************************************************************/
		EventArgs(void) : handled(0) {}
		virtual ~EventArgs(void) {}


		/*************************************************************************
			Data members
		*************************************************************************/
		//! handlers should increment this if they handled the event.
		uint handled;
	};

} // End of  Ogre namespace section

#endif	// end of guard _CEGUIEventArgs_h_
