/********************************************************************
	created:	2012/10/10
	created:	10:10:2012   22:30
	filename: 	f:\vc\work\card\Card修改2010.11.16\客户端组件\游戏广场\ResourceDecl.h
	file path:	f:\vc\work\card\Card修改2010.11.16\客户端组件\游戏广场
	file base:	ResourceDecl
	file ext:	h
	author:		bbsssssss
	
	purpose:	资源路径定义头文件
*********************************************************************/
#ifndef ResourceDecl_h__
#define ResourceDecl_h__

#define IDB_CONNECT_STATUS                        "UI\\CONNECT_STATUS.bmp"
#define IDB_SERVER_LIST_IMAGE                     "UI\\SERVER_LIST_IMAGE.bmp"
#define IDB_USER_STATUS                           "UI\\USER_STATUS.bmp"
#define IDB_BT_EXPESSION                          "UI\\BT_EXPESSION.bmp"
#define IDB_BT_SEND_CHAT                          "UI\\BT_SEND_CHAT.bmp"
#define IDB_BT_COLOR_SET                          "UI\\BT_COLOR_SET.bmp"
#define IDB_BT_CLEAN_SCREEN                       "UI\\BT_CLEAN_SCREEN.bmp"
#define IDB_BT_PHRASE                             "UI\\BT_PHRASE.bmp"
#define IDB_FRAME_CLOSE                           "UI\\FRAME_CLOSE.bmp"
#define IDB_BAR_LEFT                              "UI\\BAR_LEFT.bmp"
#define IDB_BAR_MIN                               "UI\\BAR_MIN.bmp"
#define IDB_BAR_RIGHT                             "UI\\BAR_RIGHT.bmp"
#define IDB_BAR_ITEM                              "UI\\BAR_ITEM.bmp"
#define IDB_OP_BACKGROUND                         "UI\\OP_BACKGROUND.bmp"
#define IDB_OP_NORMAL                             "UI\\OP_NORMAL.bmp"
#define IDB_OP_HOT                                "UI\\OP_HOT.bmp"
#define IDB_OP_ACTIVE                             "UI\\OP_ACTIVE.bmp"
#define IDB_SERVER_BL                             "UI\\SERVER\\SERVER_BL.bmp"
#define IDB_SERVER_BM                             "UI\\SERVER\\SERVER_BM.bmp"
#define IDB_SERVER_BR                             "UI\\SERVER\\SERVER_BR.bmp"
#define IDB_SERVER_LM                             "UI\\SERVER\\SERVER_LM.bmp"
#define IDB_SERVER_RM                             "UI\\SERVER\\SERVER_RM.bmp"
#define IDB_SERVER_TL                             "UI\\SERVER\\SERVER_TL.bmp"
#define IDB_SERVER_TM                             "UI\\SERVER\\SERVER_TM.bmp"
#define IDB_SERVER_TR                             "UI\\SERVER\\SERVER_TR.bmp"
#define IDB_WEB_BL                                "UI\\WEB\\WEB_BL.bmp"
#define IDB_WEB_BM                                "UI\\WEB\\WEB_BM.bmp"
#define IDB_WEB_BR                                "UI\\WEB\\WEB_BR.bmp"
#define IDB_WEB_LM                                "UI\\WEB\\WEB_LM.bmp"
#define IDB_WEB_RM                                "UI\\WEB\\WEB_RM.bmp"
#define IDB_WEB_TL                                "UI\\WEB\\WEB_TL.bmp"
#define IDB_WEB_TM                                "UI\\WEB\\WEB_TM.bmp"
#define IDB_WEB_TR                                "UI\\WEB\\WEB_TR.bmp"
#define IDB_TABLE_BL                              "UI\\TABLE\\TABLE_BL.bmp"
#define IDB_TABLE_BM                              "UI\\TABLE\\TABLE_BM.bmp"
#define IDB_TABLE_BR                              "UI\\TABLE\\TABLE_BR.bmp"
#define IDB_TABLE_LM                              "UI\\TABLE\\TABLE_LM.bmp"
#define IDB_TABLE_RM                              "UI\\TABLE\\TABLE_RM.bmp"
#define IDB_TABLE_TL                              "UI\\TABLE\\TABLE_TL.bmp"
#define IDB_TABLE_TM                              "UI\\TABLE\\TABLE_TM.bmp"
#define IDB_TABLE_TR                              "UI\\TABLE\\TABLE_TR.bmp"
#define IDB_LEFT_VIEW_LM                          "UI\\LEFT_VIEW\\LEFT_VIEW_LM.bmp"
#define IDB_LEFT_VIEW_MM                          "UI\\LEFT_VIEW\\LEFT_VIEW_MM.bmp"
#define IDB_LEFT_VIEW_RM                          "UI\\LEFT_VIEW\\LEFT_VIEW_RM.bmp"
#define IDB_LEFT_VIEW_LTM                         "UI\\LEFT_VIEW\\LEFT_VIEW_LTM.bmp"
#define IDB_LEFT_VIEW_RTM                         "UI\\LEFT_VIEW\\LEFT_VIEW_RTM.bmp"
#define IDB_LEFT_VIEW_LT                          "UI\\LEFT_VIEW\\LEFT_VIEW_LT.bmp"
#define IDB_LEFT_VIEW_MT                          "UI\\LEFT_VIEW\\LEFT_VIEW_MT.bmp"
#define IDB_LEFT_VIEW_RT                          "UI\\LEFT_VIEW\\LEFT_VIEW_RT.bmp"
#define IDB_LEFT_VIEW_LB                          "UI\\LEFT_VIEW\\LEFT_VIEW_LB.bmp"
#define IDB_LEFT_VIEW_MB                          "UI\\LEFT_VIEW\\LEFT_VIEW_MB.bmp"
#define IDB_LEFT_VIEW_RB                          "UI\\LEFT_VIEW\\LEFT_VIEW_RB.bmp"
#define IDB_LEFT_VIEW_LBM                         "UI\\LEFT_VIEW\\LEFT_VIEW_LBM.bmp"
#define IDB_LEFT_VIEW_RBM                         "UI\\LEFT_VIEW\\LEFT_VIEW_RBM.bmp"
#define IDB_TABLE_LOCK                            "UI\\TABLE_LOCK.bmp"
#define IDB_TABLE_READY                           "UI\\TABLE_READY.bmp"
#define IDB_FRAME_TL                              "UI\\FRAME_TL.bmp"
#define IDB_FRAME_TM                              "UI\\FRAME_TM.bmp"
#define IDB_FRAME_TR                              "UI\\FRAME_TR.bmp"
#define IDB_FRAME_L                               "UI\\FRAME_L.bmp"
#define IDB_FRAME_R                               "UI\\FRAME_R.bmp"
#define IDB_FRAME_BT_BUTTON_4                     "UI\\FRAME_BT_BUTTON_4.bmp"
#define IDB_FRAME_BT_BUTTON_3                     "UI\\FRAME_BT_BUTTON_3.bmp"
#define IDB_FRAME_BT_BUTTON_2                     "UI\\FRAME_BT_BUTTON_2.bmp"
#define IDB_FRAME_BT_BUTTON_1                     "UI\\FRAME_BT_BUTTON_1.bmp"
#define IDB_FACE_NORMAL                           "UI\\FACE_NORMAL.bmp"
#define IDB_BT_SEARCH_USER                        "UI\\BT_SEARCH_USER.bmp"
#define IDB_BT_AUTO_JOIN                          "UI\\BT_AUTO_JOIN.bmp"
#define IDB_BAR_BUTTON_FRIEND                     "UI\\BAR_BUTTON_FRIEND.bmp"
#define IDB_BAR_BUTTON_QUIT                       "UI\\BAR_BUTTON_QUIT.bmp"
#define IDB_BAR_BUTTON_NUMBER                     "UI\\BAR_BUTTON_NUMBER.bmp"
#define IDB_BAR_BUTTON_SET                        "UI\\BAR_BUTTON_SET.bmp"
#define IDB_BAR_ITEM_HOME                         "UI\\BAR_ITEM_HOME.bmp"
#define IDB_FRAME_BT_BUTTON_5                     "UI\\FRAME_BT_BUTTON_5.bmp"
#define IDB_BT_QUIT_ROOM                          "UI\\BT_QUIT_ROOM.bmp"
#define IDB_BT_WEB_BEFORE                         "UI\\BT_WEB_BEFORE.bmp"
#define IDB_BT_WEB_BRUSH                          "UI\\BT_WEB_BRUSH.bmp"
#define IDB_BT_WEB_HOME                           "UI\\BT_WEB_HOME.bmp"
#define IDB_BT_WEB_NEXT                           "UI\\BT_WEB_NEXT.bmp"
#define IDB_BT_WEB_STOP                           "UI\\BT_WEB_STOP.bmp"

#define IDB_FRAME_RESORE                          "UI\\FRAME_RESORE.bmp"
#define IDB_USER_INFO_R                           "UI\\USER_INFO_R.bmp"
#define IDB_USER_INFO_L                           "UI\\USER_INFO_L.bmp"
#define IDB_USER_INFO_M                           "UI\\USER_INFO_M.bmp"
#define IDB_DIAMOND_BLUE                          "UI\\DIAMOND_BLUE.bmp"
#define IDB_DIAMOND_RED                           "UI\\DIAMOND_RED.bmp"

#define IDB_FRAME_MAX								"UI\\FRAME_MAX.bmp"
#define IDB_FRAME_MIN								"UI\\FRAME_MIN.bmp"

#endif // ResourceDecl_h__
