//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlaza.rc
//
#define IDD_GAME_PLAZA                  102
#define IDD_SHORT_MESSAGE               110
#define IDD_FIND_USER                   111
#define IDD_MANAGER_RIGHT               115
#define IDR_MAINFRAME                   128
#define IDS_MAIN_TITLE                  129
#define IDD_GAME_ROOM                   130
#define IDD_LOGON                       132
#define IDR_MENU                        134
#define IDD_STATUS                      136
#define IDB_CONNECT_STATUS              137
#define IDB_SERVER_LIST_IMAGE           142
#define IDB_USER_STATUS                 144
#define IDD_OPTION                      181
#define IDD_ENTER_TABLE_PASS            182
#define IDD_OPTION_SYSTEM               183
#define IDC_HAND_CUR                    209
#define IDB_TABLE_LOCK                  230
#define IDB_TABLE_READY                 231
#define IDD_SEND_WARNING                262
#define IDD_REGISTER                    266
#define IDD_MANAGER_MESSAGE             267
#define IDD_MANAGER_SERVER              268
#define IDD_USER_INFO                   272
#define IDD_OPTION_TABLE_RULE           273
#define IDD_CUSTOM_FACE                 276
#define IDD_MODIFY_INDIVIDUAL           277
#define IDD_LOCKCOMPUTER                318
#define IDD_BANK_DIALOG                 320
#define IDB_BT_QUIT                     321
#define IDB_BT_LOGON                    322
#define IDB_BT_LOGON_ITEM               323
#define IDB_BT_LOGON_LINK               324
#define IDD_DLG_ENQUIRE                 324
#define IDB_BT_REGISTER_CLOSE           325
#define IDD_DIALOG1                     325
#define IDD_DLG_SERVICE                 325
#define IDB_BT_REGISTER                 326
#define IDB_BT_ENQUIRE_CANCEL           327
#define IDB_BK_ENQUIRE_BUTTON           328
#define IDB_BT_Register                 329
#define IDB_BT_Delete                   330
#define IDB_BT_NetOption                331
#define IDB_BT_Close                    332
#define IDB_BT_REGISTER_ENTER           333
#define IDB_BT_REGISTER_QUIT            334
#define IDD_DLG_SERVICE_BROWSER         350
#define IDD_DLG_SERVICE_PASSWORD        351
#define IDD_DLG_SERVICE_INDIVIDUAL      352
#define IDC_CHAT_MESSAGE                1002
#define IDC_TABLE_PASSWORD              1003
#define IDC_SERVER                      1004
#define IDC_ACCOUNTS                    1005
#define IDC_PASSWORD                    1006
#define IDC_REM_PASSWORD                1007
#define IDC_SPREADER                    1008
#define IDC_DELETE_RECORD               1009
#define IDC_SEND_SHORT                  1010
#define IDC_PASSWORD2                   1011
#define IDC_BIND_USER                   1012
#define IDC_NET_OPTION                  1013
#define IDC_REGISTER                    1014
#define IDC_RECV_MESSAGE                1015
#define IDC_BIND_GAME                   1016
#define IDC_LOGON_TYPE                  1017
#define IDC_SEND_MESSAGE                1018
#define IDC_NAME                        1019
#define IDC_MAIN_PAGE                   1020
#define IDC_ACCID                       1021
#define IDC_PASSWORD_PROTECT            1022
#define IDC_GET_PASSWORD                1023
#define IDC_REG_WEB                     1024
#define IDC_PROXY_TEST                  1025
#define IDC_PROXY_TYPE                  1026
#define IDC_PROXY_SERVER                1027
#define IDC_PROXY_USER                  1028
#define IDC_PROXY_PORT                  1029
#define IDC_LIST                        1030
#define IDC_PROXY_PASS                  1031
#define IDC_BORDER                      1032
#define IDC_USER_ID                     1033
#define IDC_CLOSE                       1034
#define IDC_TYPE_NAME                   1035
#define IDC_BRING_TABLE_PASSWORD        1036
#define IDC_VOR_SPLITER                 1037
#define IDC_CHAT_INPUT                  1038
#define IDC_AUTO_SIT                    1039
#define IDC_SEND_CHAT                   1040
#define IDC_EXPRESSION                  1041
#define IDC_PHRASE                      1042
#define IDC_COLOR_SET                   1043
#define IDC_FIND_USER                   1045
#define IDC_LIMIT_IP                    1046
#define IDC_QUIT_ROOM                   1047
#define IDC_LIMIT_FLEE_RATE             1048
#define IDC_BUGLE                       1049
#define IDC_FLEE_RATE                   1050
#define IDC_BANK                        1051
#define IDC_LIMIT_SCORE                 1052
#define IDC_USER_LIST                   1053
#define IDC_CLEAN_SCREEN                1054
#define IDC_LIMIT_DETEST                1054
#define IDC_LIMIT_WIN_RATE              1055
#define IDC_WIN_RATE                    1056
#define IDC_SCORE_LESS                  1057
#define IDC_SAVE_NONE                   1058
#define IDC_SAVE_ACCOUNTS               1059
#define IDC_SAVE_ACCOUNTS_AND_PASS      1060
#define IDC_CHAT_OBJECT                 1061
#define IDC_USER_FACE                   1062
#define IDC_PRIVIEW                     1063
#define IDC_WARNING_MESSAGE             1064
#define IDC_ROOM_CHAT                   1065
#define IDC_GAME_MESSAGE                1066
#define IDC_GAME_CHAT                   1067
#define IDC_ROOM_MESSAGE                1068
#define IDC_SEND_WISPER                 1069
#define IDC_SYSTEM_MESSAGE              1070
#define IDC_PLAY_GAME                   1071
#define IDC_LOOKON_GAME                 1072
#define IDC_SET_SHALL_CLOSE             1073
#define IDC_LIMIT_WISPER                1074
#define IDC_RADIO1                      1075
#define IDC_LIMIT_ROOM_CHAT             1076
#define IDC_RADIO2                      1077
#define IDC_GENDER                      1078
#define IDC_LIMIT_ENTER_GAME            1079
#define IDC_RADIO3                      1080
#define IDC_OPEN_CHAT_MESSAGE           1081
#define IDC_BROWSER                     1082
#define IDC_LIMIT_GAME_CHAT             1083
#define IDC_SHOW_INOUT                  1084
#define IDC_HOR_SPLITER                 1085
#define IDC_UPLOAD                      1086
#define IDC_SCORE_MAX                   1087
#define IDC_LIMIT_ENTER_ROOM            1088
#define IDC_ENTER_TABLE_PASSWORD        1089
#define IDC_DELETE                      1090
#define IDC_LogonPws                    1091
#define IDC_WARIMG_MSG                  1092
#define IDC_LOCKTEXT                    1093
#define IDC_PLAZA_FACE                  1094
#define IDC_TABLERULE                   1095
#define IDC_GAME_FACE                   1096
#define IDC_BANKPASS                    1097
#define IDC_EDIT2                       1098
#define IDC_BANKPASS2                   1099
#define IDC_TAB_BANK                    1100
#define IDC_RESET_SHALL_CLOSE           1101
#define IDC_ALLOW_WISPER                1102
#define IDC_EDIT3                       1103
#define IDC_ALLOW_ROOM_CHAT             1104
#define IDC_GAMEGOLD                    1104
#define IDC_EDIT4                       1105
#define IDC_ALLOW_ENTER_GAME            1106
#define IDC_BANKGOLD                    1106
#define IDC_BANK_TEXT                   1107
#define IDC_ALLOW_GAME_CHAT             1108
#define IDC_EDIT5                       1108
#define IDC_BOSS_HOTKEY                 1109
#define IDC_BANKPW_TEXT                 1109
#define IDC_EDIT1                       1110
#define IDC_ALLOW_ENTER_ROOM            1111
#define IDC_EDIT6                       1111
#define IDC_BACNK_BTNOK                 1112
#define IDC_EDIT_SFZ                    1112
#define IDC_BANK_PLYNAME                1113
#define IDC_EDIT_PHONE                  1113
#define IDC_BANK_PLYNICK                1114
#define IDC_COMBO1                      1114
#define IDC_BANK_BTNALL                 1115
#define IDC_BT_MAINPAGE                 1115
#define IDC_BT_NEWUSER                  1116
#define IDC_BT_SERVER                   1117
#define IDC_BUTTON4                     1118
#define IDC_BT_FINDPASSWORD             1118
#define IDC_SWITCH_ACCOUNTS             1119
#define IDC_BUTTON1                     1120
#define IDC_CLOSE_PLAZA                 1120
#define IDC_BT_                         1120
#define IDC_BT_QUIT                     1120
#define IDC_SELECT_FACE                 1121
#define IDC_GENDER_MANKIND              1123
#define IDC_GENDER_FEMALE               1124
#define IDC_UNDER_WRITE                 1125
#define IDC_COMPELLATION                1126
#define IDC_SFZ                         1127
#define IDC_MOBILE_PHONE                1128
#define IDC_QQ                          1129
#define IDC_EMAIL                       1130
#define IDC_DWELLING_PLACE              1131
#define IDC_USER_NOTE                   1132
#define IDC_NOTE                        1133
#define IDC_LOGON_PASSWORD1             1135
#define IDC_GAMEID                      1135
#define IDC_LOGON_PASSWORD2             1136
#define IDC_LOGON_PASSWORD3             1137
#define IDC_MODIFY_LOGON_PASSWORD       1138
#define IDC_INSURE_PASSWORD1            1139
#define IDC_INSURE_PASSWORD2            1140
#define IDC_INSURE_PASSWORD3            1141
#define IDC_MODIFY_INSURE_PASSWORD      1142
#define IDM_LOGON_PLAZA                 32772
#define IDM_CONNECT_SERVER              32774
#define IDM_CANCEL_CONNECT              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1136
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
