#ifndef _____Og2dKeyCode_H
#define _____Og2dKeyCode_H

namespace Og2d
{
	//! √√æŸº¸≈Ã ‰»Î¥˙¬Î
	typedef enum EKEY_CODE
	{
		EKEY_LBUTTON          = 0x01,
		EKEY_RBUTTON          = 0x02,
		EKEY_CANCEL           = 0x03,
		EKEY_MBUTTON          = 0x04,
		EKEY_XBUTTON1         = 0x05,  
		EKEY_XBUTTON2         = 0x06,  
		EKEY_BACK             = 0x08,  
		EKEY_TAB              = 0x09,  
		EKEY_CLEAR            = 0x0C, 
		EKEY_RETURN           = 0x0D, 
		EKEY_SHIFT            = 0x10, 
		EKEY_CONTROL          = 0x11, 
		EKEY_MENU             = 0x12,  
		EKEY_PAUSE            = 0x13, 
		EKEY_CAPITAL          = 0x14,  
		EKEY_KANA             = 0x15,  
		EKEY_HANGUEL          = 0x15,
		EKEY_HANGUL           = 0x15,
		EKEY_JUNJA            = 0x17, 
		EKEY_FINAL            = 0x18,  
		EKEY_HANJA            = 0x19, 
		EKEY_KANJI            = 0x19,  
		EKEY_ESCAPE           = 0x1B, 
		EKEY_CONVERT          = 0x1C,  
		EKEY_NONCONVERT       = 0x1D,  
		EKEY_ACCEPT           = 0x1E, 
		EKEY_MODECHANGE       = 0x1F, 
		EKEY_SPACE            = 0x20,  
		EKEY_PRIOR            = 0x21, 
		EKEY_NEXT             = 0x22, 
		EKEY_END              = 0x23,  
		EKEY_HOME             = 0x24,  
		EKEY_LEFT             = 0x25,  
		EKEY_UP               = 0x26, 
		EKEY_RIGHT            = 0x27,  
		EKEY_DOWN             = 0x28,  
		EKEY_SELECT           = 0x29,  
		EKEY_PRINT            = 0x2A,  
		EKEY_EXECUT           = 0x2B,  
		EKEY_SNAPSHOT         = 0x2C,  
		EKEY_INSERT           = 0x2D,  
		EKEY_DELETE           = 0x2E,  
		EKEY_HELP             = 0x2F,  
		EKEY_KEY_0            = 0x30, 
		EKEY_KEY_1            = 0x31, 
		EKEY_KEY_2            = 0x32,
		EKEY_KEY_3            = 0x33, 
		EKEY_KEY_4            = 0x34,  
		EKEY_KEY_5            = 0x35, 
		EKEY_KEY_6            = 0x36, 
		EKEY_KEY_7            = 0x37,  
		EKEY_KEY_8            = 0x38,  
		EKEY_KEY_9            = 0x39,  
		EKEY_KEY_A            = 0x41, 
		EKEY_KEY_B            = 0x42,  
		EKEY_KEY_C            = 0x43,  
		EKEY_KEY_D            = 0x44,  
		EKEY_KEY_E            = 0x45,  
		EKEY_KEY_F            = 0x46, 
		EKEY_KEY_G            = 0x47,  
		EKEY_KEY_H            = 0x48, 
		EKEY_KEY_I            = 0x49,  
		EKEY_KEY_J            = 0x4A,  
		EKEY_KEY_K            = 0x4B,  
		EKEY_KEY_L            = 0x4C, 
		EKEY_KEY_M            = 0x4D,  
		EKEY_KEY_N            = 0x4E,  
		EKEY_KEY_O            = 0x4F,  
		EKEY_KEY_P            = 0x50, 
		EKEY_KEY_Q            = 0x51, 
		EKEY_KEY_R            = 0x52,  
		EKEY_KEY_S            = 0x53, 
		EKEY_KEY_T            = 0x54, 
		EKEY_KEY_U            = 0x55,  
		EKEY_KEY_V            = 0x56,  
		EKEY_KEY_W            = 0x57,  
		EKEY_KEY_X            = 0x58, 
		EKEY_KEY_Y            = 0x59,  
		EKEY_KEY_Z            = 0x5A, 
		EKEY_LWIN             = 0x5B,
		EKEY_RWIN             = 0x5C,
		EKEY_APPS             = 0x5D,
		EKEY_SLEEP            = 0x5F,
		EKEY_NUMPAD0          = 0x60,
		EKEY_NUMPAD1          = 0x61,
		EKEY_NUMPAD2          = 0x62,
		EKEY_NUMPAD3          = 0x63,
		EKEY_NUMPAD4          = 0x64,
		EKEY_NUMPAD5          = 0x65,
		EKEY_NUMPAD6          = 0x66,
		EKEY_NUMPAD7          = 0x67,
		EKEY_NUMPAD8          = 0x68,
		EKEY_NUMPAD9          = 0x69,
		EKEY_MULTIPLY         = 0x6A,
		EKEY_ADD              = 0x6B,
		EKEY_SEPARATOR        = 0x6C,
		EKEY_SUBTRACT         = 0x6D,
		EKEY_DECIMAL          = 0x6E,
		EKEY_DIVIDE           = 0x6F,
		EKEY_F1               = 0x70,
		EKEY_F2               = 0x71,
		EKEY_F3               = 0x72,
		EKEY_F4               = 0x73,
		EKEY_F5               = 0x74,
		EKEY_F6               = 0x75,
		EKEY_F7               = 0x76,
		EKEY_F8               = 0x77,
		EKEY_F9               = 0x78,
		EKEY_F10              = 0x79,
		EKEY_F11              = 0x7A,
		EKEY_F12              = 0x7B,
		EKEY_F13              = 0x7C,
		EKEY_F14              = 0x7D,
		EKEY_F15              = 0x7E,
		EKEY_F16              = 0x7F,
		EKEY_F17              = 0x80,
		EKEY_F18              = 0x81,
		EKEY_F19              = 0x82,
		EKEY_F20              = 0x83,
		EKEY_F21              = 0x84,
		EKEY_F22              = 0x85,
		EKEY_F23              = 0x86,
		EKEY_F24              = 0x87,
		EKEY_NUMLOCK          = 0x90,
		EKEY_SCROLL           = 0x91,
		EKEY_LSHIFT           = 0xA0,
		EKEY_RSHIFT           = 0xA1,
		EKEY_LCONTROL         = 0xA2,
		EKEY_RCONTROL         = 0xA3,
		EKEY_LMENU            = 0xA4,
		EKEY_RMENU            = 0xA5,
		EKEY_PLUS             = 0xBB,
		EKEY_COMMA            = 0xBC,
		EKEY_MINUS            = 0xBD,
		EKEY_PERIOD           = 0xBE,
		EKEY_ATTN             = 0xF6,
		EKEY_CRSEL            = 0xF7,
		EKEY_EXSEL            = 0xF8,
		EKEY_EREOF            = 0xF9,
		EKEY_PLAY             = 0xFA,
		EKEY_ZOOM             = 0xFB, 
		EKEY_PA1              = 0xFD, 
		EKEY_OEM_CLEAR        = 0xFE,  

		EKEY_KEY_CODES_COUNT  = 0xFF 
	}KeyCode;

#ifndef LOWORDINT
#define LOWORDINT(n) ((int)((signed short)(LOWORD(n))))
#endif

#ifndef HIWORDINT
#define HIWORDINT(n) ((int)((signed short)(HIWORD(n))))
#endif

#ifndef Og2dKeyDown
#define Og2dKeyDown(key) (GetAsyncKeyState(key) & 0x8000 ? 1 : 0)
#endif

}

#endif