#ifndef _____OgreTerrainPropertyNameDef_H
#define _____OgreTerrainPropertyNameDef_H

#define PV_TERRAINSIZE					"TerrainSize"
#define PV_TERRAINSIZE_DESC				"set terrain size"
#define PV_WORLDSIZE					"WorldSize"
#define PV_WORLDSIZE_DESC				"set world size"
#define PV_INPUTSCALE					"InputScale"
#define PV_INPUTSCALE_DESC				"Set input scale"
#define PV_MINBATCHSIZE					"MinBatchSize"
#define PV_MINBATCHSIZE_DESC			"set min batch size"
#define PV_MAXBATCHSIZE					"MaxBatchSize"
#define PV_MAXBATCHSIZE_DESC			"set max batch size"
#define PV_MAXPIXELERROR				"MaxPixelError"
#define PV_MAXPIXELERROR_DESC			"set max pixel error"
#define PV_COMPOSITEMAPDISCANE			"CompositeMapDistance"
#define PV_COMPOSITEMAPDISCANE_DESC		"set composite map distance"
#define PV_ORIGIN						"Origin"
#define PV_OGIGIN_DESC					"set origin"
#define PV_LIGHTMAPDIRECTION			"LightMapDirection"
#define PV_LIGHTMAPDIRECTION_DESC		"set light map direction"
#define PV_COMPOSITEMAPDIFFUSE			"CompositeMapDiffuse"
#define PV_COMPOSITEMAPDIFFUSE_DESC		"set composite map diffuse"
#define PV_TERRAINPAGE_POSTION			"TerrainPagePostion"
#define PV_TERRAINPAGE_POSTION_DESC		"set terrain page position"
#define PV_TERRAINPAGE_X				"TerrainPageX"
#define	PV_TERRAINPAGE_X_DESC			"set terrain page X"
#define PV_TERRAINPAGE_Y				"TerrainPageY"
#define PV_TERRAINPAGE_Y_DESC			"set terrain page Y"

#endif