#ifndef _____OgreTerrainPropertyNameDef_H
#define _____OgreTerrainPropertyNameDef_H

#define PY_NAME_TERRAINSIZE					"TerrainSize"
#define PY_NAME_TERRAINSIZE_DESC			"set terrain size"
#define PY_NAME_WORLDSIZE					"WorldSize"
#define PY_NAME_WORLDSIZE_DESC				"set world size"
#define PY_NAME_INPUTSCALE					"InputScale"
#define PY_NAME_INPUTSCALE_DESC				"Set input scale"
#define PY_NAME_MINBATCHSIZE				"MinBatchSize"
#define PY_NAME_MINBATCHSIZE_DESC			"set min batch size"
#define PY_NAME_MAXBATCHSIZE				"MaxBatchSize"
#define PY_NAME_MAXBATCHSIZE_DESC			"set max batch size"
#define PY_NAME_MAXPIXELERROR				"MaxPixelError"
#define PY_NAME_MAXPIXELERROR_DESC			"set max pixel error"
#define PY_NAME_COMPOSITEMAPDISCANE			"CompositeMapDistance"
#define PY_NAME_COMPOSITEMAPDISCANE_DESC	"set composite map distance"
#define PY_NAME_ORIGIN						"Origin"
#define PY_NAME_OGIGIN_DESC					"set origin"
#define PY_NAME_LIGHTMAPDIRECTION			"LightMapDirection"
#define PY_NAME_LIGHTMAPDIRECTION_DESC		"set light map direction"
#define PY_NAME_COMPOSITEMAPDIFFUSE			"CompositeMapDiffuse"
#define PY_NAME_COMPOSITEMAPDIFFUSE_DESC	"set composite map diffuse"
#define PY_NAME_TERRAINPAGE_POSTION			"TerrainPagePostion"
#define PY_NAME_TERRAINPAGE_POSTION_DESC	"set terrain page position"
#define PY_NAME_TERRAINPAGE_X				"TerrainPageX"
#define	PY_NAME_TERRAINPAGE_X_DESC			"set terrain page X"
#define PY_NAME_TERRAINPAGE_Y				"TerrainPageY"
#define PY_NAME_TERRAINPAGE_Y_DESC			"set terrain page Y"

#endif